# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('theme', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30, unique=True)),
                ('mail', models.EmailField(max_length=45, unique=True)),
                ('md5_password', models.CharField(max_length=255)),
                ('online_status', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateField(auto_now_add=True)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatar_img')),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'subscribe',
                'managed': False,
            },
        ),
    ]
