INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add log entry', 1, 'add_logentry');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change log entry', 1, 'change_logentry');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete log entry', 1, 'delete_logentry');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add permission', 2, 'add_permission');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change permission', 2, 'change_permission');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete permission', 2, 'delete_permission');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add group', 3, 'add_group');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change group', 3, 'change_group');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete group', 3, 'delete_group');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add user', 4, 'add_user');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change user', 4, 'change_user');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete user', 4, 'delete_user');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add content type', 5, 'add_contenttype');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change content type', 5, 'change_contenttype');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete content type', 5, 'delete_contenttype');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add session', 6, 'add_session');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change session', 6, 'change_session');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete session', 6, 'delete_session');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add article', 7, 'add_article');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change article', 7, 'change_article');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete article', 7, 'delete_article');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add comment', 8, 'add_comment');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change comment', 8, 'change_comment');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete comment', 8, 'delete_comment');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add profile', 9, 'add_profile');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change profile', 9, 'change_profile');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete profile', 9, 'delete_profile');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add subscribe', 10, 'add_subscribe');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change subscribe', 10, 'change_subscribe');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete subscribe', 10, 'delete_subscribe');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can add userprofile', 11, 'add_userprofile');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can change userprofile', 11, 'change_userprofile');
INSERT INTO blog_db.auth_permission (name, content_type_id, codename) VALUES ('Can delete userprofile', 11, 'delete_userprofile');